### ISSUE TITLE
Decide what to do about Authentication moving forward

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/wcc-auth#2]
Decide what to do w.r.t. Authentication across our apps. Options
1) Continue to use our current oauth - requires writing some customization code for Rock.
2) Transfer people over to Rock. Use Rock's OAuth for other apps.

What is the value of maintaining our own authentication mechanism?

**Comment by jpowell** [comment]
- [ ] Mike to talk with Spark about them implementing a custom OAuth to Nucleus
- [ ] Investigate development environment (MS SQL + IIS + everything else) with newspring on Thursday - Team
- [ ] Investigate how much effort to abstract WCC:auth to use Rock OAuth (delay this task until we know more)
